### ISSUE TITLE
Bug in docs

### ISSUE THREAD

**Issue by NiedziolkaMichal** [suites-dev/automock.dev#4]
Hey,
I have started to read your documentation and the page https://automock.dev/docs/getting-started/examples to see how automock works and I get very confused by the step 2, which would now throw TS errors. `import { Database, UserService } from './user.service'; ` is missing. Overall I think it would be better to replace it with an example from readme

**Comment by omermorad** [comment]
Hello @NiedziolkaMichal,

I appreciate you pointing this out to me and posting it. It is essential that the examples provided on the documentation website be as clear as possible. I will handle it 🚀 

In the meanwhile, are you in need of assistance?

**Comment by NiedziolkaMichal** [comment]
No, thanks
